// Code generated by "stringer -type=StrictArity -trimprefix=StrictArityFlag -output=strictarity_stringer_generated.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StrictArityFlagCallSignature-1]
	_ = x[StrictArityFlagConstructSignature-2]
	_ = x[StrictArityFlagMethodSignature-4]
	_ = x[StrictArityFlagMethodDeclaration-8]
	_ = x[StrictArityFlagConstructor-16]
	_ = x[StrictArityFlagFunctionDeclaration-32]
	_ = x[StrictArityFlagFunctionExpression-64]
	_ = x[StrictArityFlagArrowFunction-128]
	_ = x[StrictArityFlagFunctionType-256]
	_ = x[StrictArityFlagConstructorType-512]
	_ = x[StrictArityNone-0]
	_ = x[StrictArityAll-1023]
}

const (
	_StrictArity_name_0 = "StrictArityNoneCallSignatureConstructSignature"
	_StrictArity_name_1 = "MethodSignature"
	_StrictArity_name_2 = "MethodDeclaration"
	_StrictArity_name_3 = "Constructor"
	_StrictArity_name_4 = "FunctionDeclaration"
	_StrictArity_name_5 = "FunctionExpression"
	_StrictArity_name_6 = "ArrowFunction"
	_StrictArity_name_7 = "FunctionType"
	_StrictArity_name_8 = "ConstructorType"
	_StrictArity_name_9 = "StrictArityAll"
)

var _StrictArity_index_0 = [...]uint8{0, 15, 28, 46}

func (i StrictArity) String() string {
	switch {
	case i <= 2:
		return _StrictArity_name_0[_StrictArity_index_0[i]:_StrictArity_index_0[i+1]]
	case i == 4:
		return _StrictArity_name_1
	case i == 8:
		return _StrictArity_name_2
	case i == 16:
		return _StrictArity_name_3
	case i == 32:
		return _StrictArity_name_4
	case i == 64:
		return _StrictArity_name_5
	case i == 128:
		return _StrictArity_name_6
	case i == 256:
		return _StrictArity_name_7
	case i == 512:
		return _StrictArity_name_8
	case i == 1023:
		return _StrictArity_name_9
	default:
		return "StrictArity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
